# 테스트 작성시 프로파일을 지정하지 않는 경우는...
spring:
  datasource:
    url:  jdbc:h2:mem:multi
    username: SA
    password:
  flyway:
    enabled: false

---
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306
    username: root
    password: 1234
  flyway:
    enabled: false
  config:
    activate:
      on-profile: local

---
#spring:
#  datasource:
#    url:  jdbc:h2:mem:multi-dev
#    username: dbdev
#    password: dbdevpassword
#  flyway:
#    enabled: false
#  config:
#    activate:
#      on-profile: dev
#
#---
#spring:
#  datasource:
#    url:  jdbc:h2:mem:multi-stage
#    username: dbstage
#    password: dbstagepassword
#  flyway:
#    enabled: false
#  config:
#    activate:
#      on-profile: stage
#
#---
#spring:
#  datasource:
#    url:  jdbc:h2:mem:multi-prod
#    username: dbprod
#    password: dbprodpassword
#  flyway:
#    enabled: false
#  config:
#    activate:
#      on-profile: prod